### ISSUE TITLE
Using the trellis

### ISSUE THREAD

**Issue by eSoares** [veeresht/CommPy#67]
Hello, 
This is not a issue with the code, more with trying to understand and using it.
I'm trying to simulate 802.11, and having difficulties with which parameters are the right to use to build the Trellis instance.
I have found a paper indicating the generator polynomials g0= 1011011 and g1= 1111001 [1], but to use it in this framework?
Like this `g_matrix = np.array(((1, 0, 1, 1, 0, 1, 1), (1, 1, 1, 1, 0, 0, 1)), ndmin=2)`?

Also, how to build the different coding rates of 802.11 (1/2, 3/4, 5/6)?

Thanks for the help.

[1] - (page 19) https://pdfs.semanticscholar.org/c63b/71e43dc23b17ca57267f3b769224c64d5e33.pdf

**Comment by BastienTr** [comment]
82.11 is not a straight-forward standard and I don't know how to implement the different coding rates offhand. To be honest, I don't have time to dig on this topic but if you have a precise question at some point, fell free to ask. You should have a look at the optional parameter `puncture_matrix` of `conv_encode`. The functions `punctering` and `depuncturing` written by @kirlf in the same file. They are not tested yet so that they are not in the Commpy interface. I never used them and I don't know how they work but they might be useful for you.

https://github.com/veeresht/CommPy/blob/1d26b074818ad3a56fe7baa70c92b04ab575f612/commpy/channelcoding/convcode.py#L476-L492

Regarding the generator polinomials that you provide. We have to assume that g0 and g1 are expressed as binary arrays. [1] doesn't give any precision but it make sense to me. You have to convert g0 and g1 to the decimal equivalent. I use the MSB-first format that is more intuitive to me but you could have used LSB-first. The conversion is possible by hand or using commpy.utilities.bitarray2dec`. The following code whould do the trick:

``` Python
from commpy.utilities import bitarray2dec
from commpy.channelcoding.convcode import Trellis
from numpy import array

# Convert g0 and g1 to decimal
g0 = bitarray2dec(array((1, 0, 1, 1, 0, 1, 1)))
g1 = bitarray2dec(array((1, 1, 1, 1, 0, 0, 1)))

# Build memory and generator matrix
memory = array(6, ndmin=1)  # "The encoder uses a 6-stage shift register." ([1] p.19)
generator_matrix = array((g0, g1), ndmin=2)

# Build Treillis
Trellis(memory, generator_matrix)
```

**Comment by BastienTr** [comment]
If you manage to build a tested 802.11 transmission, would you mind to share it here? We could use it as en axample or break it to functions in Commpy? It would be even better if you do it yourself and write a PR but the file would already be a great share.

**Comment by BastienTr** [comment]
Hi @eSoares,
I hope your implementation is going well. I close this issue but please feel free to reopen it or start a new one if you have any questions or come up with something you agree to share.
